Python
Python中编写多线程程序的时候，既然有GIL为何还需要进行线程间的同步操作？
GIL知识保证同一时刻只有一个线程可以执行bytecodes和操作全局变量字典
知道Python版的解释器PyPy是如何实现的吗？
PyPy是用C版本CPython解释器支持的Python语言实现的
Python与C/C++交互有哪些方法？
使用原生的Python/C API编写扩展模块，使用ctypes调用，使用Boost.Python或者SWIG调用；使用Cython把Python代码转换成C/C++
Python是如何实现来及回收的？
引用计数和分代回收
Python中不使用临时变量如何交换两个整形数？
a=a+b; b=a-b; a=a-b; （缺点，可能溢出）
a = a ^ b; b = a ^ b; a = a ^ b;（一个数和另一个数异或两次得到的还是原来的数）
a, b = b, a
Python中静态函数, 类函数和成员函数有什么区别?
静态函数(@staticmethod): 即静态方法，主要处理与这个类的逻辑关联
类函数(@classmethod):即类方法, 更关注于从类中调用方法，而不是在实例中调用方法
成员函数: 实例的方法, 只能通过实例进行调用
—————————————————————————————————- more

什么是PEP 8? – PEP8是一个编码规范
用过pickling and unpickling？ – Pickle module accepts any Python object and converts it into a string representation and dumps it into a file
python内存怎么管理？- Python memory is managed by Python private heap space. All Python objects and data structures are located in a private heap. The programmer does not have an access to this private heap and interpreter takes care of this Python private heap.
The allocation of Python heap space for Python objects is done by Python memory manager. The core API gives access to some tools for the programmer to code.
Python also have an inbuilt garbage collector, which recycle all the unused memory and frees the memory and makes it available to the heap space.
什么是Python decorators？
list 和tuple的区别？ – list and tuple is that list is mutable while tuple is not. Tuple can be hashed for e.g as a key for dictionaries.
How are arguments passed by value or by reference?
什么是Dict List comprehensions? – syntax constructions to ease the creation of a Dictionary or List based on existing iterable
python有哪些build-in type? mutable: List, Sets, Dictionaries 和 inmutable: Strings,Tuples, NumbersStrings
python lambda? single expression anonymous function often used as inline function.
In Python what is slicing? A mechanism to select a range of items from sequence types like list, tuple, strings etc. is known as slicing.
python 中，如何copy object? copy.copy () or copy.deepcopy
copy.copy () or copy.deepcopy 区别？
如何共享global variables across modules？ share global variables across modules within a single program, create a special module. Import the config module in all modules of your application. The module will be available as a global variable across modules.
如何通过python删文件？ – os.remove (filename) or os.unlink(filename)
python如何获得随机数？- import random random.random()
说说 Django, Pyramid, and Flask的区别？
how to overload constructors or methods in Python？
python “with” 的用法，需要实现什么函数？enter(), exit()
What are negative indexes and why are they used?
What is the difference between .py and .pyc files ? – python files are Python source files. .pyc files are the compiled bvtecode files that is generated by the Python compiler.
作者 yaojie
发布于 2018年3月6日
分类 home

列表和元组的区别
*args, **kwargs的含义
打乱一个列表：shuffle
字符串列表拼接 ”.join, 比循环+拼接高效
迭代器，生成器的区别
Python的装饰器，上下文管理器的作用和使用场景
staticmethod classmethod区别
Python要实现一个框架，提供灵活性的方式有哪些，有什么缺点如何避免（面试非常熟悉Python的人）

运算符重载
getattr等标准接口
元类
ast模块
eval

性能

测量性能的方法和工具

自己计时
Ipython %timeit
line_prof vprof 等

提升性能的方法

列表推导，尽量使用标准库实现的功能而不是自动动手实现
缓存结果
改进算法
多核并行mutiprocessing
编译级别优化Cython, weave, numba, pypy等

Numpy

Numpy ndarray的存储结构，广播的含义
Numpy 矩阵的运算背后的加速机制有哪些

Pandas

如何过滤出某列的值在一个指定集合内的行 df[df.name.isin([‘A’, ‘B’])]
缺失值填充的方法 fillna
按照某个字段分组统计价格的的OHLC grouby

开发调试部署

使用什么可以实现Python版本及其库的隔离：virtualenv python
如何有效地组织一个Python项目：自动化测试，持续集成，文档
如何实现远程开发调试部署

安装发布，适合面比较有经验的人

命令行接口如何实现：argparser, google-fire
如何发布： python 使用setup.py 安装，使用entry_point封装成命令行工具
